fix: docker building workflow
Change-Id: I7330fda5766ed3eb84f5b4c53a01e010ec7d8fc4
Signed-off-by: Peter Mikus <peter.mikus@icloud.com>

diff --git a/.github/workflows/csit-executor-tg.yaml b/.github/workflows/csit-executor-tg.yaml
--- a/.github/workflows/csit-executor-tg.yaml
+++ b/.github/workflows/csit-executor-tg.yaml
@@ -42,6 +42,19 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
 
+      - name: Start docker daemon
+        shell: bash
+        env:
+          START_DOCKER_SCRIPT: start-docker.sh
+        run: |
+          if [ -n "$(which $START_DOCKER_SCRIPT)" ] ; then
+            cat "$(which $START_DOCKER_SCRIPT)"
+            $START_DOCKER_SCRIPT
+          else
+            echo "Docker startup script not found on PATH: $START_DOCKER_SCRIPT"
+            exit 1
+          fi
+
       - name: Cache Docker layers
         id: actions_cache
         uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
